### ISSUE TITLE
Priorities for the Website

### ISSUE THREAD

**Issue by skimbro1** [skimbro1/CCC#1]
## PRIORITIES ##

**ACCESS**
- [x] Add appropriate members
- [x] ~~Set up google email, calendar and drive~~
- [x] Add staff to staff page
- [x] get photos from in front of brick wall

- [x] get brief bio of elders, Deacon, staff @skimbro1
  *  requested on 3/16 for 3/20 delivery and update to site

**GENERAL**
- [x]  Determine which sections to keep and which to not use
- [x]  Need to find or create digital image for Lent/Proverbs series
- [x]  Work with Dustin & Whitney on the Parish Project integration
- [ ]  Need to find digital images for Good Friday, Easter
- [x]  Need to upload sermons
- [ ]  Need to resize Logo [Moved to Issue #2]

** Main Page **
- [x] Need digital content - photos for Rotator
- [x] Proverbs series
- [x] Lent

**About Us**
- [x]  Need fresh Content
- [x]  Need photos

**Membership Class**
- [ ]  Need info from Bill on what to include here (should be brief)

**Prayer Meeting**
- [ ]  prayer request form?
- [x]  Need to create a brief content for this module
- [x]  Need to add it to the Events / Calendar

**Mission**
- [x]  Need to create a Missions section
- [x] Need to talk to Sam about content

**Kids**
- [ ]  Need to fill out the Sunday School / Kids info
- [ ]  Need digital images?

**Blog**
- [x] Title?  Which sidebar?

**Comment by skimbro1** [comment]
- [ ] Find out from Bill about Shutterstock

**Comment by skimbro1** [comment]
Add picture to rotator.  Consider adding rotator to another page. - like a get connected page.

**Comment by skimbro1** [comment]
@skimbro1

**Comment by skimbro1** [comment]
**Community Group**

7:00-8:00

State contact Dustin if interested

**Comment by skimbro1** [comment]
Click here if already a member for schedule

**Comment by skimbro1** [comment]
Check on membership self management

**Comment by skimbro1** [comment]
@skimbro1 i talked to the video producer

**Comment by skimbro1** [comment]
# Meeting Notes #
## Original House of Pancakes 3/16/2017 ##




### Next Steps ###

1.  **Add a Missions Page to Ministry section.**

- [ ] Scott to get in touch with Sam Wyman to discuss vision and content.
- [ ] Probably will need pictures, brief bios, and work being done by various missionaries.

2.  **Need better content for Kids Page.**

- [ ] Asking Bill Lovell to look at that and think about what he wants there.

3.  **Pastor Blog**

- [ ] Asking Bill Lovell to think of a name for the blog so I can create it.

4.  **Logo**

- [ ] Asking Bill to think about changing the logo.  He knows a graphic artist.  Need to ask him/her to come up with some designs.  I think we should create something more modern.

5. **Theme/color changes to website.

- [ ] Discussed changing the colors of the buttons, could even be pictures if wanted.

6.   **Next Meeting**

- [ ] Schedule next meeting w/ Agenda (see below).

_____________________

### Agenda for Next Meeting ###

- [ ] Walk through how the site is structured on the backend
- [ ] Walk through the backend use of Ekk360 for Blogging
- [ ] Walk through how to use GitHub
- [ ] Get photos from old website; e.g. the one of Ellen and ones of kids if available.  
- [ ] Discuss photos - need photos for website
- [ ] Discuss what wants for the Kids page - or potentially other pages:
* Membership?
* Baptism?
* Weddings?

- [ ] Discuss forms?  
* Prayer requests

- [ ] Discuss Giving.  In advance @skimbro1 will look into what is needed from CCC to start the process.

**Comment by wlovell** [comment]
@skimbro1 - I'm contemplating blog names!

**Comment by skimbro1** [comment]
@wlovell - great

**Comment by wlovell** [comment]
@skimbro1 - This time with watching and star!

**Comment by wlovell** [comment]
@skimbro1 - Ethos = friendly, warm, welcoming - the love of Christ

**Comment by wlovell** [comment]
We love people
              young people
              old people
              rich people
              poor people
              organized people
              messed up people
              all people                    
Because Christ first love us.

**Comment by skimbro1** [comment]
@wlovell I think the above could go as text on a slide/photo for the about us page

**Comment by wlovell** [comment]
1 John 4:19 "We love because he first loved us."

**Comment by skimbro1** [comment]
@wlovell - you'll notice that at the bottom of the box when you add a comment there's "Styling with Markdown is supported".  Click on that if you want to make your comments fancy - bold, italics, lists, headings, etc.

**Comment by skimbro1** [comment]
@wlovell - requested bio from elders/deacon for 3/20

**Comment by skimbro1** [comment]
Closing Thread - moving remaining action items to individual issues.
