### ISSUE TITLE
Logo Redesign

### ISSUE THREAD

**Issue by wlovell** [skimbro1/CCC#2]
- [ ] Identify qualified graphic designer
- [ ] Discuss project & terms
- [ ] Introduce to Scott
- [ ] Get started on a logo
- [ ] Give feedback
- [ ] Complete logo

**Comment by wlovell** [comment]
A friend recommended Alexa Rearick (?) as a good graphic designer. I reached out to her the other day, and she just responded a few hours ago. Emailing her now. I'll copy you. 

979-574-7877
alm.rearick

**Comment by skimbro1** [comment]
https://www.linkedin.com/in/almrearick/

**Comment by wlovell** [comment]
Just wrote Alexa. Copied you.

**Comment by skimbro1** [comment]
@wlovell got it.  Also, once you figure out if she's a good fit, we can invite here to collaborate here.
