### ISSUE TITLE
Pastor's Blog

### ISSUE THREAD

**Issue by wlovell** [skimbro1/CCC#3]

**Comment by skimbro1** [comment]
@wlovell - here's the blog layout

http://layouts.ekklesia360.com/blog-layout-1/

**Comment by skimbro1** [comment]
@wlovell - now that you've got a sense for the Blog and the Articles functions.  Let's discuss syndication on Facebook, how to publish as draft, syndication guidelines, and things to think through.

For instance, in some cases, depending upon which YouTube video you choose, some of the "recommended videos" that appear to the right might not be what we want to direct people to, as an example.

We have 50GB of storage so we'll want to Embed videos as much as possible.

Also, you'll want to click on the "Preview Page" button and "Publish as Draft" first to review it.

As to Facebook integration, there should be a checkbox that is available that will result in it automatically posting to Facebook as soon as you click "Publish" - hence why it's wise to sleep on it or give it some, or give it editorial review prior to posting, by posting as Draft.

**Comment by skimbro1** [comment]
Cirlcing the square has launched.  Closing issue.
